name: fwfh_just_audio
version: 0.6.1
description: WidgetFactory extension to render AUDIO with the just_audio plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  just_audio: ^0.7.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.6.0 <0.8.0"
  
  # rxdart version should be kept in sync with `just_audio`
  # https://github.com/ryanheise/just_audio/blob/master/just_audio/pubspec.yaml
  rxdart: ^0.26.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
